# Dataverse schema reference for LLM prompt and validation

# Claims table and fields
claim_table = "smvs_claims"
claim_fields = [
    "smvs_claimid",
    "smvs_name",
    "smvs_claimed_amount",
    "smvs_expected_amount_claim",
    "smvs_balance_currency",
    "smvs_recieved_amount",
    "smvs_claimstatus",
    "smvs_internal_state",
    "statuscode",
    "statecode",
    "smvs_remark",
    "smvs_error_description",
    "smvs_fulfilleddate",
    "createdon",
    "modifiedon",
    "_smvs_patientid_value",
    "_smvs_rendering_provider_key_value",
    "_smvs_ordering_physician_key_value",
    "_smvs_insuranceorganization_value",
    "smvs_claim_type",
    "smvs_internal_claim_type",
    "smvs_billing_type",
    "smvs_payment_type",
    "smvs_box1plantype",
    "smvs_box6patientrelationshiptoinsured",
    "smvs_box21diagnosisindicator",
    "smvs_box24ediagnosispointer",
    "smvs_box26patientsaccountnumber",
    "smvs_box33billingproviderlastname",
    "smvs_box33anpi",
    "smvs_total_days",
    "smvs_needs_review",
    "smvs_is_forwarded_claim"
]

# Service line table and fields
service_line_table = "smvs_service_lines"
service_line_fields = [
    "smvs_servicelineid",
    "smvs_name",
    "smvs_serviceline_control_number",
    "_smvs_claimid_value",
    "smvs_ncpdpclaimid",
    "smvs_proceduresservicesorsupplies",
    "_smvs_cpt_hcpcs_code_value",
    "smvs_product_service_id",
    "smvs_product_service_id_qualifier",
    "smvs_modifiers",
    "smvs_additional_modifiers",
    "smvs_diagnosispointer",
    "smvs_charges",
    "smvs_expected_amount_service_line",
    "smvs_expected_amount_service_line_base",
    "smvs_other_payer_insurance_paid_amount",
    "smvs_other_payer_insurance_paid_amount_base",
    "smvs_datesofservice",
    "smvs_dateofserviceto",
    "smvs_other_payer_check_processed_date",
    "smvs_placeofservice",
    "smvs_place_of_service_experimental",
    "smvs_dayorunitvalue",
    "smvs_daysorunits",
    "smvs_product_service_unit_count",
    "smvs_product_service_unit_measurement_code",
    "smvs_unitmeasurementcode",
    "smvs_nationaldrugcode",
    "smvs_ndc_number",
    "smvs_nationaldrugunitcount",
    "_smvs_ndc_code_key_value",
    "smvs_renderingproviderid",
    "smvs_renderingprovidernpi",
    "_smvs_rendering_provider_value",
    "smvs_idqualifier",
    "smvs_prior_authorization_number",
    "_smvs_prior_authorization_id_value",
    "smvs_additional_service_line_information",
    "_smvs_vaccine_key_value",
    "statuscode",
    "statecode",
    "smvs_isactive",
    "smvs_ignoreforclaimsubmission",
    "smvs_emg",
    "smvs_epsdtorfamilyplan",
    "smvs_order",
    "createdon",
    "modifiedon",
    "_createdby_value",
    "_modifiedby_value",
    "_createdonbehalfby_value",
    "_modifiedonbehalfby_value",
    "_ownerid_value",
    "_owninguser_value",
    "_owningteam_value",
    "_owningbusinessunit_value",
    "_transactioncurrencyid_value",
    "exchangerate",
    "importsequencenumber",
    "overriddencreatedon",
    "timezoneruleversionnumber",
    "utcconversiontimezonecode",
    "versionnumber",
    "@odata.etag"
]

# Combined schema for prompt or validation

dataverse_schema = {
    claim_table: claim_fields,
    service_line_table: service_line_fields
}
